[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Security-Policy = "img-src 'self' data:"
    Content-Type = "application/javascript"
